-- MySQL Script generated by MySQL Workbench
-- Thu Dec 21 18:27:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CarRentalSystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CarRentalSystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CarRentalSystem` DEFAULT CHARACTER SET utf8 ;
USE `CarRentalSystem` ;

-- -----------------------------------------------------
-- Table `CarRentalSystem`.`office`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarRentalSystem`.`office` (
  `office_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `phone_No` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `building_No` VARCHAR(45) NULL,
  PRIMARY KEY (`office_id`),
  UNIQUE INDEX `office_id_UNIQUE` (`office_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarRentalSystem`.`Car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarRentalSystem`.`Car` (
  `plate_id` VARCHAR(8) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `make` VARCHAR(45) NOT NULL,
  `year` VARCHAR(45) NOT NULL,
  `price` DOUBLE NOT NULL,
  `registration_date` DATE NULL DEFAULT CURRENT_TIMESTAMP,
  `office_office_id` INT NOT NULL,
  `status` BOOLEAN DEFAULT false,
  PRIMARY KEY (`plate_id`),
  UNIQUE INDEX `plate_id_UNIQUE` (`plate_id` ASC) ,
  INDEX `fk_Car_office1_idx` (`office_office_id` ASC) ,
  CONSTRAINT `fk_Car_office1`
    FOREIGN KEY (`office_office_id`)
    REFERENCES `CarRentalSystem`.`office` (`office_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarRentalSystem`.`Car_Photos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarRentalSystem`.`Car_Photos` (
  `photo` VARCHAR(512) NOT NULL,
  `Car_plate_id` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`photo`, `Car_plate_id`),
  INDEX `fk_Car_Photos_Car_idx` (`Car_plate_id` ASC) ,
  CONSTRAINT `fk_Car_Photos_Car`
    FOREIGN KEY (`Car_plate_id`)
    REFERENCES `CarRentalSystem`.`Car` (`plate_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarRentalSystem`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarRentalSystem`.`Customer` (
  `ssn` INT NOT NULL AUTO_INCREMENT,
  `fName` VARCHAR(45) NOT NULL,
  `lName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone_no` CHAR(11) NOT NULL,
  `password` VARCHAR(45) NULL,
  `wallet` DOUBLE NULL,
  PRIMARY KEY (`ssn`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarRentalSystem`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarRentalSystem`.`reservation` (
  `reservation_no` INT NOT NULL,
  `reserve_date` DATE NOT NULL,
  `pickup_date` DATE NOT NULL,
  `return_date` DATE NOT NULL,
  `pickup_location` VARCHAR(45) NULL,
  `Car_plate_id` VARCHAR(8) NOT NULL,
  `Customer_ssn` INT NOT NULL,
  `payment_date` VARCHAR(45) NULL,
  `payment_Method` VARCHAR(45) NULL,
  PRIMARY KEY (`reservation_no`),
  INDEX `fk_reservation_Car1_idx` (`Car_plate_id` ASC) ,
  INDEX `fk_reservation_Customer1_idx` (`Customer_ssn` ASC) ,
  CONSTRAINT `fk_reservation_Car1`
    FOREIGN KEY (`Car_plate_id`)
    REFERENCES `CarRentalSystem`.`Car` (`plate_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_Customer1`
    FOREIGN KEY (`Customer_ssn`)
    REFERENCES `CarRentalSystem`.`Customer` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarRentalSystem`.`credit_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarRentalSystem`.`credit_card` (
  `card_no` INT NOT NULL,
  `holder_name` VARCHAR(100) NOT NULL,
  `CVV` CHAR(3) NOT NULL,
  `exp_date` DATE NOT NULL,
  PRIMARY KEY (`card_no`),
  UNIQUE INDEX `card_no_UNIQUE` (`card_no` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarRentalSystem`.`customer_credit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarRentalSystem`.`customer_credit` (
  `ssn` INT NOT NULL,
  `credit_card_card_no` INT NOT NULL,
  `Customer_ssn` INT NOT NULL,
  PRIMARY KEY (`ssn`, `credit_card_card_no`, `Customer_ssn`),
  INDEX `fk_customer_credit_credit_card1_idx` (`credit_card_card_no` ASC) ,
  INDEX `fk_customer_credit_Customer1_idx` (`Customer_ssn` ASC) ,
  CONSTRAINT `fk_customer_credit_credit_card1`
    FOREIGN KEY (`credit_card_card_no`)
    REFERENCES `CarRentalSystem`.`credit_card` (`card_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_credit_Customer1`
    FOREIGN KEY (`Customer_ssn`)
    REFERENCES `CarRentalSystem`.`Customer` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarRentalSystem`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CarRentalSystem`.`Admin` (
  `email` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
